"""
Mock connector — reads the synthetic Parquet files generated by data_generator.

Simulates real API behaviour: pagination, incremental filtering,
batch metadata, and health checks.
"""

from __future__ import annotations
import logging
from datetime import datetime
from pathlib import Path
from typing import Any, Iterator

import pandas as pd

from ingestion.base import BaseConnector, ConnectorError

logger = logging.getLogger(__name__)

_DEFAULT_DATA_DIR = Path("data/synthetic")
_BATCH_SIZE = 500


class MockConnector(BaseConnector):
    """
    Reads synthetic Parquet files and yields DataFrames in batches,
    mimicking a paginated REST API.

    Config keys (all optional):
      data_dir  : path to the synthetic data directory
      batch_size: rows per yielded batch
    """

    source_name = "mock"

    def __init__(self, source: str, config: dict[str, Any]) -> None:
        super().__init__(config)
        self._source_label = source
        self._data_dir = Path(config.get("data_dir", _DEFAULT_DATA_DIR))
        self._batch_size = int(config.get("batch_size", _BATCH_SIZE))

    # ── Lifecycle ─────────────────────────────────────────────────────────────

    def _do_authenticate(self) -> None:
        if not self._data_dir.exists():
            raise ConnectorError(
                f"Mock data directory not found: {self._data_dir}. "
                "Run `python -m data_generator` first."
            )

    def _do_health_check(self) -> bool:
        return self._data_dir.exists()

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _load_parquet(self, name: str) -> pd.DataFrame:
        path = self._data_dir / f"{name}.parquet"
        if not path.exists():
            raise ConnectorError(f"Synthetic file not found: {path}")
        return pd.read_parquet(path)

    def _paginate(
        self,
        df: pd.DataFrame,
        since: datetime | None,
        date_col: str | None,
        entity: str,
    ) -> Iterator[pd.DataFrame]:
        """Filter by `since` date, attach metadata, and yield in batches."""
        if since is not None and date_col and date_col in df.columns:
            df = df[pd.to_datetime(df[date_col]) >= pd.Timestamp(since)]

        batch_id = self.make_batch_id()
        total = len(df)
        logger.info("[mock/%s] %s  rows=%d  batch_size=%d", entity, self._source_label, total, self._batch_size)

        for start in range(0, max(total, 1), self._batch_size):
            chunk = df.iloc[start: start + self._batch_size]
            if chunk.empty:
                break
            yield self.add_ingestion_metadata(chunk, source=f"mock/{entity}", batch_id=batch_id)

    # ── Public data methods ───────────────────────────────────────────────────

    def get_customers(self, since: datetime | None = None, **_) -> Iterator[pd.DataFrame]:
        df = self._load_parquet("customers")
        yield from self._paginate(df, since, "signup_date", "customers")

    def get_products(self, since: datetime | None = None, **_) -> Iterator[pd.DataFrame]:
        df = self._load_parquet("products")
        yield from self._paginate(df, None, None, "products")

    def get_orders(self, since: datetime | None = None, **_) -> Iterator[pd.DataFrame]:
        df = self._load_parquet("orders")
        yield from self._paginate(df, since, "order_date", "orders")

    def get_order_items(self, since: datetime | None = None, **_) -> Iterator[pd.DataFrame]:
        df = self._load_parquet("order_items")
        yield from self._paginate(df, None, None, "order_items")

    def get_payments(self, since: datetime | None = None, **_) -> Iterator[pd.DataFrame]:
        df = self._load_parquet("payments")
        yield from self._paginate(df, since, "payment_date", "payments")

    def get_refunds(self, since: datetime | None = None, **_) -> Iterator[pd.DataFrame]:
        df = self._load_parquet("refunds")
        yield from self._paginate(df, since, "refund_date", "refunds")

    def get_inventory(self, since: datetime | None = None, **_) -> Iterator[pd.DataFrame]:
        df = self._load_parquet("inventory")
        yield from self._paginate(df, since, "date", "inventory")

    def get_shipments(self, since: datetime | None = None, **_) -> Iterator[pd.DataFrame]:
        df = self._load_parquet("shipments")
        yield from self._paginate(df, since, "shipped_date", "shipments")

    def get_ad_spend(self, since: datetime | None = None, **_) -> Iterator[pd.DataFrame]:
        df = self._load_parquet("advertising")
        yield from self._paginate(df, since, "date", "advertising")

    def get_payouts(self, since: datetime | None = None, **_) -> Iterator[pd.DataFrame]:
        df = self._load_parquet("payouts")
        yield from self._paginate(df, since, "payout_date", "payouts")
